Create Table If Not Exists users(
    id BigInt Generated By Default As Identity Not Null,
    login Character Varying(128) Collate pg_catalog.default Not Null,
    password Character Varying(1024) Collate pg_catalog.default Not Null,
    Constraint pk_users Primary Key(id),
    Constraint uq_login Unique(login)
) Tablespace pg_default;

Create Table If Not Exists roles(
    id BigInt Generated By Default As Identity Not Null,
    code Character Varying(32) Collate pg_catalog.default Not Null,
    description Character Varying(256) Collate pg_catalog.default,
    Constraint pk_roles Primary Key(id),
    Constraint uq_code Unique(code)
) Tablespace pg_default;

Create Table If Not Exists users_and_roles(
    user_id BigInt Not Null,
    role_id BigInt Not Null,
    Constraint pk_users_and_roles Primary Key(user_id, role_id),
    Constraint fk_users Foreign Key(user_id) References users(id) On Delete Cascade On Update Restrict,
    Constraint fk_roles Foreign Key(role_id) References roles(id) On Delete Cascade On Update Restrict
) Tablespace pg_default;