Create Table If Not Exists files(
    id BigInt Generated By Default As Identity Not Null,
    name Character Varying(128) Collate pg_catalog.default Not Null,
    type Character Varying(128) Collate pg_catalog.default Not Null,
    size BigInt Not Null,
    data ByteA Not Null,
    hash Character Varying(256) Collate pg_catalog.default Not Null,
    user_id BigInt Not Null,
    is_deleted Boolean Not Null,
    Constraint pk_files Primary Key (id),
    Constraint fk_users Foreign Key (user_id) References users (id) On Delete Cascade On Update Restrict
) Tablespace pg_default;